<h1>Pagina de Edição</h1>

<hr>

<form action="#" method="POST">
    <label>Nome</label>
    <input type="hidden" name="id" value="<?php echo $_POST["nome"] ?? $aluno['id'];?>">
    <label>Matricula</label>
    <input type="text" name="matricula" value="<?php echo $_POST["matricula"] ?? $aluno['matricula'];?>">
    <label>Cidade</label>
    <input type="text" name="cidade" value="<?php echo $_POST["cidade"] ?? $aluno['cidade'];?>">
    <button type="submit">Criar</button>
</form>