<h1>Pagina de Listar</h1>

<hr>

<table class="container table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <td>ID</td>
            <td>Nome</td>
            <td>Matricula</td>
            <td>Cidade</td>
            <td>Ações</td>
        </tr>
    </thead>

    <tbody>
    <?php
    foreach ($dados as $row){
        $id = $row['id'];
        echo "<tr>
        <td>{$row['id']}</td>
        <td>{$row['nome']}</td>
        <td>{$row['matricula']}</td>
        <td>{$row['cidade']}</td>
        <td>
            <a href='/editar?id=({$id})' class ='btn btn-outline-warning'>EDITAR</a>
            <button type='button' onclick='excluirid({$id})' data-bs-toggle='modal' data-bs-target='#exampleModal' class='btn btn-outline-danger'>Excluir</button>
        </td>
        </tr>";
    }
     ?>   

    </tbody>
   
</table>

<!-- Modal -->
<div class='modal fade' id='exampleModal' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='exampleModalLabel'>Apagar aluno cadastrado</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                Confirma a exclusão do aluno?
                <input type="hidden" id="idatual">
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <button type='button' onclick='confirmar()' class='btn btn-danger'>Excluir</button> 
            </div>
        </div>
    </div>
</div>

<script>

function excluirid(id) {
        document.getElementById("idatual").value = id;
    }

    function confirmar(id){
        if(true === confirm('tem certeza?')){
            location.href = '/excluir?id='+id;
        }
    }
</script>

<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js'
    integrity='sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3'
    crossorigin='anonymous'>
</script>


    