<h1>Pagina de Cadastro</h1>

<hr>

<form action="#" method="POST">
    <label>Nome</label>
    <input required value="<?php echo $_POST['nome'] ?? ''?>" type="text" name="nome">
    <label>Matricula</label>
    <input required value="<?php echo $_POST['matricula'] ?? ''?>" type="text" name="matricula">
    <label>Cidade</label>
    <input required value="<?php echo $_POST['cidade'] ?? ''?>" type="text" name="cidade">
    <button type="submit">Criar</button>
</form>